networks:
  traefik:
    name: traefik
    external: true

services:
  guacd:
    container_name: guacd
    image: guacamole/guacd
    networks:
      traefik:
    restart: unless-stopped
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw

  postgres:
    container_name: guac_postgres
    hostname: guac_postgres
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guac_db
      POSTGRES_USER: guac_user
      POSTGRES_PASSWORD: ${DB_PASS}
    image: postgres:15.2-alpine
    networks:
      traefik:
    restart: unless-stopped
    volumes:
    - ./init:/docker-entrypoint-initdb.d:z
    - ./data:/var/lib/postgresql/data:Z

  # guacamole
  guacamole:
    container_name: cyberchef
    depends_on:
      - guacd
      - postgres
    env_file:
      - .env
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guac_db
      POSTGRES_HOSTNAME: guac_postgres
      POSTGRES_USER: guac_user
      POSTGRES_PASSWORD: ${DB_PASS}
    image: guacamole/guacamole
    links:
      - guacd
    networks:
      traefik:
    expose:
      - 8080
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.guac.tls: true
      traefik.http.routers.guac.tls.certresolver: production
      traefik.http.routers.guac.middlewares: guacamole-prefix
      traefik.http.middlewares.guacamole-prefix.addprefix.prefix: "/guacamole"